from app.schemas import Project


def build_generated_files(project: Project) -> list[dict[str, str]]:
    architecture = project.artifacts.get("architecture")
    backend_plan = project.artifacts.get("backend_plan")
    qa_plan = project.artifacts.get("qa_plan")

    routes = (architecture.data.get("api_routes", []) if architecture else []) or [
        "POST /appointments",
        "GET /availability",
        "PATCH /appointments/{appointment_id}/status",
    ]
    files = (backend_plan.data.get("files", []) if backend_plan else []) or [
        "app/main.py",
        "app/models.py",
        "app/schemas.py",
        "app/routes/appointments.py",
    ]

    return [
        {
            "path": "README.md",
            "language": "markdown",
            "content": _readme(project, routes, files),
        },
        {
            "path": "requirements.txt",
            "language": "text",
            "content": "fastapi==0.115.6\nuvicorn[standard]==0.34.0\npydantic==2.10.4\n",
        },
        {
            "path": "app/__init__.py",
            "language": "python",
            "content": "",
        },
        {
            "path": "app/main.py",
            "language": "python",
            "content": _main_py(project),
        },
        {
            "path": "app/models.py",
            "language": "python",
            "content": _models_py(),
        },
        {
            "path": "app/schemas.py",
            "language": "python",
            "content": _schemas_py(),
        },
        {
            "path": "app/routes/__init__.py",
            "language": "python",
            "content": "",
        },
        {
            "path": "app/routes/appointments.py",
            "language": "python",
            "content": _appointments_route_py(),
        },
        {
            "path": "tests/test_appointments.py",
            "language": "python",
            "content": _tests_py(qa_plan.data if qa_plan else {}),
        },
    ]


def _readme(project: Project, routes: list[str], files: list[str]) -> str:
    route_lines = "\n".join(f"- `{route}`" for route in routes)
    file_lines = "\n".join(f"- `{file}`" for file in files)
    return f"""# {project.name}

Generated by AgentFlow from this product idea:

{project.idea}

## Generated File Plan

{file_lines}

## API Routes

{route_lines}

## Run

```bash
pip install -r requirements.txt
uvicorn app.main:app --reload
```
"""


def _main_py(project: Project) -> str:
    return f'''from fastapi import FastAPI

from app.routes.appointments import router as appointments_router


app = FastAPI(
    title="{project.name}",
    description="Generated starter API from AgentFlow.",
    version="0.1.0",
)

app.include_router(appointments_router)


@app.get("/health")
def health() -> dict[str, str]:
    return {{"status": "ok"}}
'''


def _models_py() -> str:
    return '''from enum import Enum
from pydantic import BaseModel


class AppointmentStatus(str, Enum):
    pending = "pending"
    approved = "approved"
    cancelled = "cancelled"
    completed = "completed"


class Appointment(BaseModel):
    id: int
    patient_name: str
    patient_email: str
    dentist_name: str
    starts_at: str
    status: AppointmentStatus = AppointmentStatus.pending
'''


def _schemas_py() -> str:
    return '''from pydantic import BaseModel, Field


class AppointmentCreate(BaseModel):
    patient_name: str = Field(min_length=1)
    patient_email: str = Field(min_length=3)
    dentist_name: str = Field(min_length=1)
    starts_at: str


class AppointmentStatusUpdate(BaseModel):
    status: str
    audit_reason: str | None = None
'''


def _appointments_route_py() -> str:
    return '''from fastapi import APIRouter, HTTPException

from app.models import Appointment, AppointmentStatus
from app.schemas import AppointmentCreate, AppointmentStatusUpdate


router = APIRouter(prefix="/appointments", tags=["appointments"])

appointments: list[Appointment] = []


@router.post("", response_model=Appointment)
def create_appointment(payload: AppointmentCreate) -> Appointment:
    for appointment in appointments:
        if (
            appointment.dentist_name == payload.dentist_name
            and appointment.starts_at == payload.starts_at
            and appointment.status != AppointmentStatus.cancelled
        ):
            raise HTTPException(status_code=409, detail="Dentist already booked for this time.")

    appointment = Appointment(id=len(appointments) + 1, **payload.model_dump())
    appointments.append(appointment)
    return appointment


@router.get("", response_model=list[Appointment])
def list_appointments() -> list[Appointment]:
    return appointments


@router.patch("/{appointment_id}/status", response_model=Appointment)
def update_appointment_status(
    appointment_id: int, payload: AppointmentStatusUpdate
) -> Appointment:
    for appointment in appointments:
        if appointment.id == appointment_id:
            if payload.status not in AppointmentStatus.__members__:
                raise HTTPException(status_code=400, detail="Invalid appointment status.")
            if payload.status == "approved" and not payload.audit_reason:
                raise HTTPException(status_code=400, detail="Approval requires an audit reason.")
            appointment.status = AppointmentStatus(payload.status)
            return appointment

    raise HTTPException(status_code=404, detail="Appointment not found.")
'''


def _tests_py(qa_plan: dict) -> str:
    test_notes = qa_plan.get("api_tests", [])
    notes = "\n".join(f"# - {item}" for item in test_notes)
    return f'''from fastapi.testclient import TestClient

from app.main import app


client = TestClient(app)


def test_health() -> None:
    assert client.get("/health").json() == {{"status": "ok"}}


def test_create_appointment() -> None:
    response = client.post(
        "/appointments",
        json={{
            "patient_name": "Maria",
            "patient_email": "maria@example.com",
            "dentist_name": "Dr. Lee",
            "starts_at": "2026-07-01T09:00:00",
        }},
    )
    assert response.status_code == 200


{notes}
'''
